### ISSUE TITLE
Implemented Homework

### ISSUE THREAD

**Issue by EYjcmkCJjf** [htl-perg-2019-20-5bhif/contact-list-exercise-EYjcmkCJjf#1]
Dear Mr. Stropek!

I tried doing my best. Unfortunately i had to use ASP.NET Core 2.1

Markus Kern

**Comment by rstropek** [comment]
Ok, no problem. Did you install .NET Core 3 in the meanwhile? Added some feedback (comments) to your code.

Greetings,
Rainer Stropek

**Comment by EYjcmkCJjf** [comment]
Yes, I installed .NET Core 3.0 twice, but I can't choose it when creating a
project. Anyways, Jakob Strasser seems to have a solution for this problem
and will help me.
Thanks for the feedback!

Am Do., 3. Okt. 2019 um 12:22 Uhr schrieb Rainer Stropek <
notifications@github.com>:
